# Generated by Django 5.2.1 on 2025-05-30 07:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=20)),
                ('raza', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado'), ('en_adopcion', 'En adopción')], default='perdido', max_length=20)),
                ('fecha_perdida', models.DateField(default=django.utils.timezone.now, verbose_name='fecha de extravío')),
                ('lugar_perdida', models.CharField(max_length=200, verbose_name='lugar donde se perdió')),
                ('telefono_contacto', models.CharField(max_length=20, verbose_name='teléfono de contacto')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='email de contacto')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de publicación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mascota',
                'verbose_name_plural': 'mascotas',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
