# Generated by Django 5.1.5 on 2025-05-31 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='país')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='biografía')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='sitio web')),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='usuario de Twitter')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='perfil de Facebook')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='usuario de Instagram')),
                ('social_auth', models.JSONField(blank=True, default=dict, verbose_name='datos de autenticación social')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfiles de usuario',
                'ordering': ['usuario__username'],
            },
        ),
    ]
